### PR TITLE
gmp conversion for 32bit systems

### PR DESCRIPTION
**Pull request by csoeger**
See issue #36 Not sure if this is the correct/optimal solution.

### CODE REVIEW

**Comment by fingolfin** [comment]
I don't think this change is correct, but neither is the current code :-). I'll work on a fix.

In the meantime, it would be great if we could add test for this somehow... What would be a good example which causes Normaliz to return a specific integer? I.e. so that we can test whether it converts numbers like 2^28, -2^28, 2^32, etc. correctly.

**Comment by fingolfin** [comment]
Actually, I take that back: It *does* look correct, and I don't get why we had that #ifdef in the original code... Huh...

It would still be nice to be able to generate tests cases.

**Comment by csoeger** [comment]
Additionally I would like to understand understand why it made a difference in the result as reported in #36

I can add test cases for the conversion. For positive values it is easy to achieve by giving generators of a simplicial cone such that the generator matrix has that value as determinant.
To check just the conversion it would also be enough to just give such numbers in the input (e.g. generators) and read back the corresponding field.

**Comment by fingolfin** [comment]
Yeah. Note that critical values would be around 2^28 and 2^60; as well as 2^32 and 2^64. ThiAnd a bit more if you also want to take sign issues into account.  I.e. I'd try   e*2^n + d,  where e is 1 or -1, d is -1, 0, 1, and n is, say, 28, 31,32, 60, 63, 64

**Pull request merged**
